# /etc/strongswan.conf on Ubuntu A
charon {
    load_modular = yes
    plugins {
        include strongswan.d/charon/*.conf
    }
    # Keep detailed logs for the capture/analysis dataset
    filelog {
        /var/log/charon.log {
            time_format = %b %e %T
            ike_name = yes
            append = no
            default = 2
            flush_line = yes
        }
    }
}

include strongswan.d/*.conf
